export const STANDARD_EMOJIS: Record<string, { emoji: string; name: string }[]> = {
  frequent: [
    { emoji: '😀', name: 'grinning face' },
    { emoji: '😂', name: 'face with tears of joy' },
    { emoji: '🥰', name: 'smiling face with hearts' },
    { emoji: '😍', name: 'smiling face with heart-eyes' },
    { emoji: '🤣', name: 'rolling on the floor laughing' },
    { emoji: '😊', name: 'smiling face with smiling eyes' },
    { emoji: '🙏', name: 'folded hands' },
    { emoji: '💕', name: 'two hearts' },
    { emoji: '😭', name: 'loudly crying face' },
    { emoji: '😘', name: 'face blowing a kiss' },
    { emoji: '👍', name: 'thumbs up' },
    { emoji: '👏', name: 'clapping hands' },
    { emoji: '🔥', name: 'fire' },
    { emoji: '🥺', name: 'pleading face' },
    { emoji: '😢', name: 'crying face' },
    { emoji: '💖', name: 'sparkling heart' },
    { emoji: '❤️', name: 'red heart' },
    { emoji: '😁', name: 'beaming face with smiling eyes' },
    { emoji: '🙌', name: 'raising hands' },
    { emoji: '🤔', name: 'thinking face' },
    { emoji: '😅', name: 'grinning face with sweat' },
    { emoji: '🎉', name: 'party popper' },
    { emoji: '🤗', name: 'hugging face' },
    { emoji: '💯', name: 'hundred points' },
    { emoji: '😩', name: 'weary face' },
    { emoji: '🤦', name: 'person facepalming' },
    { emoji: '😎', name: 'smiling face with sunglasses' },
    { emoji: '💀', name: 'skull' },
    { emoji: '✨', name: 'sparkles' },
    { emoji: '👀', name: 'eyes' },
    { emoji: '🤷', name: 'person shrugging' },
    { emoji: '😏', name: 'smirking face' },
    { emoji: '💪', name: 'flexed biceps' },
    { emoji: '💚', name: 'green heart' },
    { emoji: '💙', name: 'blue heart' },
    { emoji: '💜', name: 'purple heart' },
    { emoji: '🧡', name: 'orange heart' },
    { emoji: '💛', name: 'yellow heart' },
    { emoji: '🖤', name: 'black heart' },
    { emoji: '🤍', name: 'white heart' },
    { emoji: '🤎', name: 'brown heart' },
    { emoji: '💔', name: 'broken heart' },
    { emoji: '❣️', name: 'heart exclamation' },
    { emoji: '💞', name: 'revolving hearts' },
    { emoji: '💓', name: 'beating heart' },
    { emoji: '💗', name: 'growing heart' },
    { emoji: '💘', name: 'heart with arrow' },
    { emoji: '💝', name: 'heart with ribbon' },
    { emoji: '💟', name: 'heart decoration' },
  ],
  people: [
    { emoji: '👋', name: 'waving hand' },
    { emoji: '🤚', name: 'raised back of hand' },
    { emoji: '🖐️', name: 'hand with fingers splayed' },
    { emoji: '✋', name: 'raised hand' },
    { emoji: '🖖', name: 'vulcan salute' },
    { emoji: '👌', name: 'OK hand' },
    { emoji: '🤌', name: 'pinched fingers' },
    { emoji: '🤏', name: 'pinching hand' },
    { emoji: '✌️', name: 'victory hand' },
    { emoji: '🤞', name: 'crossed fingers' },
    { emoji: '🤟', name: 'love-you gesture' },
    { emoji: '🤘', name: 'sign of the horns' },
    { emoji: '🤙', name: 'call me hand' },
    { emoji: '👈', name: 'backhand index pointing left' },
    { emoji: '👉', name: 'backhand index pointing right' },
    { emoji: '👆', name: 'backhand index pointing up' },
    { emoji: '👇', name: 'backhand index pointing down' },
    { emoji: '☝️', name: 'index pointing up' },
    { emoji: '👍', name: 'thumbs up' },
    { emoji: '👎', name: 'thumbs down' },
    { emoji: '✊', name: 'raised fist' },
    { emoji: '👊', name: 'oncoming fist' },
    { emoji: '🤛', name: 'left-facing fist' },
    { emoji: '🤜', name: 'right-facing fist' },
    { emoji: '👏', name: 'clapping hands' },
    { emoji: '🙌', name: 'raising hands' },
    { emoji: '👐', name: 'open hands' },
    { emoji: '🤲', name: 'palms up together' },
    { emoji: '🤝', name: 'handshake' },
    { emoji: '🙏', name: 'folded hands' },
    { emoji: '✍️', name: 'writing hand' },
    { emoji: '💅', name: 'nail polish' },
    { emoji: '🤳', name: 'selfie' },
    { emoji: '💪', name: 'flexed biceps' },
    { emoji: '🦾', name: 'mechanical arm' },
    { emoji: '🦿', name: 'mechanical leg' },
    { emoji: '🦵', name: 'leg' },
    { emoji: '🦶', name: 'foot' },
    { emoji: '👂', name: 'ear' },
    { emoji: '🦻', name: 'ear with hearing aid' },
    { emoji: '👃', name: 'nose' },
    { emoji: '🧠', name: 'brain' },
    { emoji: '👀', name: 'eyes' },
    { emoji: '👁️', name: 'eye' },
    { emoji: '👅', name: 'tongue' },
    { emoji: '👄', name: 'mouth' },
    { emoji: '👶', name: 'baby' },
    { emoji: '👧', name: 'girl' },
    { emoji: '🧒', name: 'child' },
    { emoji: '👦', name: 'boy' },
    { emoji: '👩', name: 'woman' },
    { emoji: '🧑', name: 'person' },
    { emoji: '👨', name: 'man' },
    { emoji: '👵', name: 'old woman' },
    { emoji: '🧓', name: 'older person' },
    { emoji: '👴', name: 'old man' },
    { emoji: '🙍', name: 'person frowning' },
    { emoji: '🙎', name: 'person pouting' },
    { emoji: '🙅', name: 'person gesturing NO' },
    { emoji: '🙆', name: 'person gesturing OK' },
    { emoji: '💁', name: 'person tipping hand' },
    { emoji: '🙋', name: 'person raising hand' },
    { emoji: '🙇', name: 'person bowing' },
    { emoji: '🤦', name: 'person facepalming' },
    { emoji: '🤷', name: 'person shrugging' },
    { emoji: '💆', name: 'person getting massage' },
    { emoji: '💇', name: 'person getting haircut' },
    { emoji: '🚶', name: 'person walking' },
    { emoji: '🧍', name: 'person standing' },
    { emoji: '🧎', name: 'person kneeling' },
    { emoji: '🏃', name: 'person running' },
    { emoji: '💃', name: 'woman dancing' },
    { emoji: '🕺', name: 'man dancing' },
    { emoji: '🕴️', name: 'person in suit levitating' },
    { emoji: '👯', name: 'people with bunny ears' },
    { emoji: '🧖', name: 'person in steamy room' },
    { emoji: '🧘', name: 'person in lotus position' },
    { emoji: '🤴', name: 'prince' },
    { emoji: '👸', name: 'princess' },
    { emoji: '🤵', name: 'person in tuxedo' },
    { emoji: '👰', name: 'person with veil' },
    { emoji: '🤰', name: 'pregnant woman' },
    { emoji: '🤱', name: 'breast-feeding' },
    { emoji: '👼', name: 'baby angel' },
    { emoji: '🎅', name: 'Santa Claus' },
    { emoji: '🤶', name: 'Mrs. Claus' },
    { emoji: '🦸', name: 'superhero' },
    { emoji: '🦹', name: 'supervillain' },
    { emoji: '🧙', name: 'mage' },
    { emoji: '🧚', name: 'fairy' },
    { emoji: '🧛', name: 'vampire' },
    { emoji: '🧜', name: 'mermaid' },
    { emoji: '🧝', name: 'elf' },
    { emoji: '🧞', name: 'genie' },
    { emoji: '🧟', name: 'zombie' },
    { emoji: '👮', name: 'police officer' },
    { emoji: '🕵️', name: 'detective' },
    { emoji: '💂', name: 'guard' },
    { emoji: '👷', name: 'construction worker' },
  ],
  nature: [
    { emoji: '🐶', name: 'dog face' },
    { emoji: '🐕', name: 'dog' },
    { emoji: '🦮', name: 'guide dog' },
    { emoji: '🐕‍🦺', name: 'service dog' },
    { emoji: '🐩', name: 'poodle' },
    { emoji: '🐺', name: 'wolf' },
    { emoji: '🦊', name: 'fox' },
    { emoji: '🦝', name: 'raccoon' },
    { emoji: '🐱', name: 'cat face' },
    { emoji: '🐈', name: 'cat' },
    { emoji: '🐈‍⬛', name: 'black cat' },
    { emoji: '🦁', name: 'lion' },
    { emoji: '🐯', name: 'tiger face' },
    { emoji: '🐅', name: 'tiger' },
    { emoji: '🐆', name: 'leopard' },
    { emoji: '🐴', name: 'horse face' },
    { emoji: '🐎', name: 'horse' },
    { emoji: '🦄', name: 'unicorn' },
    { emoji: '🦓', name: 'zebra' },
    { emoji: '🐮', name: 'cow face' },
    { emoji: '🐂', name: 'ox' },
    { emoji: '🐃', name: 'water buffalo' },
    { emoji: '🐄', name: 'cow' },
    { emoji: '🐷', name: 'pig face' },
    { emoji: '🐖', name: 'pig' },
    { emoji: '🐗', name: 'boar' },
    { emoji: '🐽', name: 'pig nose' },
    { emoji: '🐏', name: 'ram' },
    { emoji: '🐑', name: 'ewe' },
    { emoji: '🐐', name: 'goat' },
    { emoji: '🐪', name: 'camel' },
    { emoji: '🐫', name: 'two-hump camel' },
    { emoji: '🦙', name: 'llama' },
    { emoji: '🦒', name: 'giraffe' },
    { emoji: '🐘', name: 'elephant' },
    { emoji: '🦣', name: 'mammoth' },
    { emoji: '🦏', name: 'rhinoceros' },
    { emoji: '🦛', name: 'hippopotamus' },
    { emoji: '🐭', name: 'mouse face' },
    { emoji: '🐁', name: 'mouse' },
    { emoji: '🐀', name: 'rat' },
    { emoji: '🐹', name: 'hamster' },
    { emoji: '🐰', name: 'rabbit face' },
    { emoji: '🐇', name: 'rabbit' },
    { emoji: '🐿️', name: 'chipmunk' },
    { emoji: '🦫', name: 'beaver' },
    { emoji: '🦔', name: 'hedgehog' },
    { emoji: '🦇', name: 'bat' },
    { emoji: '🐻', name: 'bear' },
    { emoji: '🐻‍❄️', name: 'polar bear' },
    { emoji: '🐨', name: 'koala' },
    { emoji: '🐼', name: 'panda' },
    { emoji: '🦥', name: 'sloth' },
    { emoji: '🦦', name: 'otter' },
    { emoji: '🦨', name: 'skunk' },
    { emoji: '🦘', name: 'kangaroo' },
    { emoji: '🦡', name: 'badger' },
    { emoji: '🐾', name: 'paw prints' },
    { emoji: '🦃', name: 'turkey' },
    { emoji: '🐔', name: 'chicken' },
    { emoji: '🐓', name: 'rooster' },
    { emoji: '🐣', name: 'hatching chick' },
    { emoji: '🐤', name: 'baby chick' },
    { emoji: '🐥', name: 'front-facing baby chick' },
    { emoji: '🐦', name: 'bird' },
    { emoji: '🐧', name: 'penguin' },
    { emoji: '🕊️', name: 'dove' },
    { emoji: '🦅', name: 'eagle' },
    { emoji: '🦆', name: 'duck' },
    { emoji: '🦢', name: 'swan' },
    { emoji: '🦉', name: 'owl' },
    { emoji: '🦤', name: 'dodo' },
    { emoji: '🪶', name: 'feather' },
    { emoji: '🦩', name: 'flamingo' },
    { emoji: '🦚', name: 'peacock' },
    { emoji: '🦜', name: 'parrot' },
    { emoji: '🐸', name: 'frog' },
    { emoji: '🐊', name: 'crocodile' },
    { emoji: '🐢', name: 'turtle' },
    { emoji: '🦎', name: 'lizard' },
    { emoji: '🐍', name: 'snake' },
    { emoji: '🐲', name: 'dragon face' },
    { emoji: '🐉', name: 'dragon' },
    { emoji: '🦕', name: 'sauropod' },
    { emoji: '🦖', name: 'T-Rex' },
    { emoji: '🐳', name: 'spouting whale' },
    { emoji: '🐋', name: 'whale' },
    { emoji: '🐬', name: 'dolphin' },
    { emoji: '🦭', name: 'seal' },
    { emoji: '🐟', name: 'fish' },
    { emoji: '🐠', name: 'tropical fish' },
    { emoji: '🐡', name: 'blowfish' },
    { emoji: '🦈', name: 'shark' },
    { emoji: '🐙', name: 'octopus' },
    { emoji: '🐚', name: 'spiral shell' },
    { emoji: '🐌', name: 'snail' },
    { emoji: '🦋', name: 'butterfly' },
    { emoji: '🐛', name: 'bug' },
    { emoji: '🐜', name: 'ant' },
    { emoji: '🐝', name: 'honeybee' },
    { emoji: '🪲', name: 'beetle' },
    { emoji: '🐞', name: 'lady beetle' },
    { emoji: '🦗', name: 'cricket' },
    { emoji: '🕷️', name: 'spider' },
    { emoji: '🕸️', name: 'spider web' },
    { emoji: '🦂', name: 'scorpion' },
    { emoji: '🦟', name: 'mosquito' },
    { emoji: '🪰', name: 'fly' },
    { emoji: '🪱', name: 'worm' },
    { emoji: '🦠', name: 'microbe' },
    { emoji: '💐', name: 'bouquet' },
    { emoji: '🌸', name: 'cherry blossom' },
    { emoji: '💮', name: 'white flower' },
    { emoji: '🏵️', name: 'rosette' },
    { emoji: '🌹', name: 'rose' },
    { emoji: '🥀', name: 'wilted flower' },
    { emoji: '🌺', name: 'hibiscus' },
    { emoji: '🌻', name: 'sunflower' },
    { emoji: '🌼', name: 'blossom' },
    { emoji: '🌷', name: 'tulip' },
    { emoji: '🌱', name: 'seedling' },
    { emoji: '🪴', name: 'potted plant' },
    { emoji: '🌲', name: 'evergreen tree' },
    { emoji: '🌳', name: 'deciduous tree' },
    { emoji: '🌴', name: 'palm tree' },
    { emoji: '🌵', name: 'cactus' },
    { emoji: '🌾', name: 'sheaf of rice' },
    { emoji: '🌿', name: 'herb' },
    { emoji: '☘️', name: 'shamrock' },
    { emoji: '🍀', name: 'four leaf clover' },
    { emoji: '🍁', name: 'maple leaf' },
    { emoji: '🍂', name: 'fallen leaf' },
    { emoji: '🍃', name: 'leaf fluttering in wind' },
    { emoji: '🌍', name: 'earth showing Europe-Africa' },
    { emoji: '🌎', name: 'earth showing Americas' },
    { emoji: '🌏', name: 'earth showing Asia-Australia' },
    { emoji: '🌐', name: 'globe with meridians' },
    { emoji: '🌑', name: 'new moon' },
    { emoji: '🌒', name: 'waxing crescent moon' },
    { emoji: '🌓', name: 'first quarter moon' },
    { emoji: '🌔', name: 'waxing gibbous moon' },
    { emoji: '🌕', name: 'full moon' },
    { emoji: '🌖', name: 'waning gibbous moon' },
    { emoji: '🌗', name: 'last quarter moon' },
    { emoji: '🌘', name: 'waning crescent moon' },
    { emoji: '🌙', name: 'crescent moon' },
    { emoji: '🌚', name: 'new moon face' },
    { emoji: '🌛', name: 'first quarter moon face' },
    { emoji: '🌜', name: 'last quarter moon face' },
    { emoji: '🌡️', name: 'thermometer' },
    { emoji: '☀️', name: 'sun' },
    { emoji: '🌝', name: 'full moon face' },
    { emoji: '🌞', name: 'sun with face' },
    { emoji: '⭐', name: 'star' },
    { emoji: '🌟', name: 'glowing star' },
    { emoji: '🌠', name: 'shooting star' },
    { emoji: '☁️', name: 'cloud' },
    { emoji: '⛅', name: 'sun behind cloud' },
    { emoji: '⛈️', name: 'cloud with lightning and rain' },
    { emoji: '🌤️', name: 'sun behind small cloud' },
    { emoji: '🌥️', name: 'sun behind large cloud' },
    { emoji: '🌦️', name: 'sun behind rain cloud' },
    { emoji: '🌧️', name: 'cloud with rain' },
    { emoji: '🌨️', name: 'cloud with snow' },
    { emoji: '🌩️', name: 'cloud with lightning' },
    { emoji: '🌪️', name: 'tornado' },
    { emoji: '🌫️', name: 'fog' },
    { emoji: '🌬️', name: 'wind face' },
    { emoji: '🌀', name: 'cyclone' },
    { emoji: '🌈', name: 'rainbow' },
    { emoji: '🌂', name: 'closed umbrella' },
    { emoji: '☂️', name: 'umbrella' },
    { emoji: '☔', name: 'umbrella with rain drops' },
    { emoji: '⛱️', name: 'umbrella on ground' },
    { emoji: '⚡', name: 'high voltage' },
    { emoji: '❄️', name: 'snowflake' },
    { emoji: '☃️', name: 'snowman' },
    { emoji: '⛄', name: 'snowman without snow' },
    { emoji: '☄️', name: 'comet' },
    { emoji: '🔥', name: 'fire' },
    { emoji: '💧', name: 'droplet' },
    { emoji: '🌊', name: 'water wave' },
  ],
  food: [
    { emoji: '🍏', name: 'green apple' },
    { emoji: '🍎', name: 'red apple' },
    { emoji: '🍐', name: 'pear' },
    { emoji: '🍊', name: 'tangerine' },
    { emoji: '🍋', name: 'lemon' },
    { emoji: '🍌', name: 'banana' },
    { emoji: '🍉', name: 'watermelon' },
    { emoji: '🍇', name: 'grapes' },
    { emoji: '🍓', name: 'strawberry' },
    { emoji: '🫐', name: 'blueberries' },
    { emoji: '🍈', name: 'melon' },
    { emoji: '🍒', name: 'cherries' },
    { emoji: '🍑', name: 'peach' },
    { emoji: '🥭', name: 'mango' },
    { emoji: '🍍', name: 'pineapple' },
    { emoji: '🥥', name: 'coconut' },
    { emoji: '🥝', name: 'kiwi fruit' },
    { emoji: '🍅', name: 'tomato' },
    { emoji: '🍆', name: 'eggplant' },
    { emoji: '🥑', name: 'avocado' },
    { emoji: '🥦', name: 'broccoli' },
    { emoji: '🥬', name: 'leafy green' },
    { emoji: '🥒', name: 'cucumber' },
    { emoji: '🌶️', name: 'hot pepper' },
    { emoji: '🫑', name: 'bell pepper' },
    { emoji: '🌽', name: 'ear of corn' },
    { emoji: '🥕', name: 'carrot' },
    { emoji: '🫒', name: 'olive' },
    { emoji: '🧄', name: 'garlic' },
    { emoji: '🧅', name: 'onion' },
    { emoji: '🥔', name: 'potato' },
    { emoji: '🍠', name: 'roasted sweet potato' },
    { emoji: '🥐', name: 'croissant' },
    { emoji: '🥯', name: 'bagel' },
    { emoji: '🍞', name: 'bread' },
    { emoji: '🥖', name: 'baguette bread' },
    { emoji: '🥨', name: 'pretzel' },
    { emoji: '🧀', name: 'cheese wedge' },
    { emoji: '🥚', name: 'egg' },
    { emoji: '🍳', name: 'cooking' },
    { emoji: '🧈', name: 'butter' },
    { emoji: '🥞', name: 'pancakes' },
    { emoji: '🧇', name: 'waffle' },
    { emoji: '🥓', name: 'bacon' },
    { emoji: '🥩', name: 'cut of meat' },
    { emoji: '🍗', name: 'poultry leg' },
    { emoji: '🍖', name: 'meat on bone' },
    { emoji: '🌭', name: 'hot dog' },
    { emoji: '🍔', name: 'hamburger' },
    { emoji: '🍟', name: 'french fries' },
    { emoji: '🍕', name: 'pizza' },
    { emoji: '🥪', name: 'sandwich' },
    { emoji: '🥙', name: 'stuffed flatbread' },
    { emoji: '🧆', name: 'falafel' },
    { emoji: '🌮', name: 'taco' },
    { emoji: '🌯', name: 'burrito' },
    { emoji: '🫔', name: 'tamale' },
    { emoji: '🥗', name: 'green salad' },
    { emoji: '🥘', name: 'shallow pan of food' },
    { emoji: '🫕', name: 'fondue' },
    { emoji: '🍝', name: 'spaghetti' },
    { emoji: '🍜', name: 'steaming bowl' },
    { emoji: '🍲', name: 'pot of food' },
    { emoji: '🍛', name: 'curry rice' },
    { emoji: '🍣', name: 'sushi' },
    { emoji: '🍱', name: 'bento box' },
    { emoji: '🥟', name: 'dumpling' },
    { emoji: '🦪', name: 'oyster' },
    { emoji: '🍤', name: 'fried shrimp' },
    { emoji: '🍙', name: 'rice ball' },
    { emoji: '🍚', name: 'cooked rice' },
    { emoji: '🍘', name: 'rice cracker' },
    { emoji: '🍥', name: 'fish cake with swirl' },
    { emoji: '🥠', name: 'fortune cookie' },
    { emoji: '🥡', name: 'takeout box' },
    { emoji: '🍦', name: 'soft ice cream' },
    { emoji: '🍧', name: 'shaved ice' },
    { emoji: '🍨', name: 'ice cream' },
    { emoji: '🍩', name: 'doughnut' },
    { emoji: '🍪', name: 'cookie' },
    { emoji: '🎂', name: 'birthday cake' },
    { emoji: '🍰', name: 'shortcake' },
    { emoji: '🧁', name: 'cupcake' },
    { emoji: '🥧', name: 'pie' },
    { emoji: '🍫', name: 'chocolate bar' },
    { emoji: '🍬', name: 'candy' },
    { emoji: '🍭', name: 'lollipop' },
    { emoji: '🍮', name: 'custard' },
    { emoji: '🍯', name: 'honey pot' },
    { emoji: '🍼', name: 'baby bottle' },
    { emoji: '🥛', name: 'glass of milk' },
    { emoji: '☕', name: 'hot beverage' },
    { emoji: '🫖', name: 'teapot' },
    { emoji: '🍵', name: 'teacup without handle' },
    { emoji: '🍶', name: 'sake' },
    { emoji: '🍾', name: 'bottle with popping cork' },
    { emoji: '🍷', name: 'wine glass' },
    { emoji: '🍸', name: 'cocktail glass' },
    { emoji: '🍹', name: 'tropical drink' },
    { emoji: '🍺', name: 'beer mug' },
    { emoji: '🍻', name: 'clinking beer mugs' },
    { emoji: '🥂', name: 'clinking glasses' },
    { emoji: '🥃', name: 'tumbler glass' },
    { emoji: '🫗', name: 'pouring liquid' },
    { emoji: '🥤', name: 'cup with straw' },
    { emoji: '🧋', name: 'bubble tea' },
    { emoji: '🧃', name: 'beverage box' },
    { emoji: '🧉', name: 'mate' },
    { emoji: '🧊', name: 'ice' },
    { emoji: '🥢', name: 'chopsticks' },
    { emoji: '🍽️', name: 'fork and knife with plate' },
    { emoji: '🍴', name: 'fork and knife' },
    { emoji: '🥄', name: 'spoon' },
    { emoji: '🔪', name: 'kitchen knife' },
    { emoji: '🏺', name: 'amphora' },
  ],
  activity: [
    { emoji: '⚽', name: 'soccer ball' },
    { emoji: '🏀', name: 'basketball' },
    { emoji: '🏈', name: 'american football' },
    { emoji: '⚾', name: 'baseball' },
    { emoji: '🥎', name: 'softball' },
    { emoji: '🎾', name: 'tennis' },
    { emoji: '🏐', name: 'volleyball' },
    { emoji: '🏉', name: 'rugby football' },
    { emoji: '🥏', name: 'flying disc' },
    { emoji: '🎱', name: 'pool 8 ball' },
    { emoji: '🪀', name: 'yo-yo' },
    { emoji: '🏓', name: 'ping pong' },
    { emoji: '🏸', name: 'badminton' },
    { emoji: '🏒', name: 'ice hockey' },
    { emoji: '🏑', name: 'field hockey' },
    { emoji: '🥍', name: 'lacrosse' },
    { emoji: '🏏', name: 'cricket game' },
    { emoji: '🥅', name: 'goal net' },
    { emoji: '⛳', name: 'flag in hole' },
    { emoji: '🪁', name: 'kite' },
    { emoji: '🏹', name: 'bow and arrow' },
    { emoji: '🎣', name: 'fishing pole' },
    { emoji: '🤿', name: 'diving mask' },
    { emoji: '🥊', name: 'boxing glove' },
    { emoji: '🥋', name: 'martial arts uniform' },
    { emoji: '🎽', name: 'running shirt' },
    { emoji: '🛹', name: 'skateboard' },
    { emoji: '🛼', name: 'roller skate' },
    { emoji: '🛷', name: 'sled' },
    { emoji: '⛸️', name: 'ice skate' },
    { emoji: '🥌', name: 'curling stone' },
    { emoji: '🎿', name: 'skis' },
    { emoji: '⛷️', name: 'skier' },
    { emoji: '🏂', name: 'snowboarder' },
    { emoji: '🏋️', name: 'person lifting weights' },
    { emoji: '🤼', name: 'people wrestling' },
    { emoji: '🤸', name: 'person cartwheeling' },
    { emoji: '⛹️', name: 'person bouncing ball' },
    { emoji: '🤺', name: 'person fencing' },
    { emoji: '🤾', name: 'person playing handball' },
    { emoji: '🏌️', name: 'person golfing' },
    { emoji: '🏇', name: 'horse racing' },
    { emoji: '🧘', name: 'person in lotus position' },
    { emoji: '🏄', name: 'person surfing' },
    { emoji: '🏊', name: 'person swimming' },
    { emoji: '🤽', name: 'person playing water polo' },
    { emoji: '🚣', name: 'person rowing boat' },
    { emoji: '🧗', name: 'person climbing' },
    { emoji: '🚴', name: 'person biking' },
    { emoji: '🚵', name: 'person mountain biking' },
    { emoji: '🎖️', name: 'military medal' },
    { emoji: '🏆', name: 'trophy' },
    { emoji: '🏅', name: 'sports medal' },
    { emoji: '🥇', name: '1st place medal' },
    { emoji: '🥈', name: '2nd place medal' },
    { emoji: '🥉', name: '3rd place medal' },
    { emoji: '🎮', name: 'video game' },
    { emoji: '🕹️', name: 'joystick' },
    { emoji: '🎲', name: 'game die' },
    { emoji: '🧩', name: 'puzzle piece' },
    { emoji: '♟️', name: 'chess pawn' },
    { emoji: '🎯', name: 'bullseye' },
    { emoji: '🎰', name: 'slot machine' },
    { emoji: '🀄', name: 'mahjong red dragon' },
    { emoji: '🃏', name: 'joker' },
    { emoji: '🎴', name: 'flower playing cards' },
    { emoji: '🎭', name: 'performing arts' },
    { emoji: '🖼️', name: 'framed picture' },
    { emoji: '🎨', name: 'artist palette' },
    { emoji: '🧵', name: 'thread' },
    { emoji: '🪡', name: 'sewing needle' },
    { emoji: '🧶', name: 'yarn' },
    { emoji: '🪢', name: 'knot' },
  ],
  travel: [
    { emoji: '🚗', name: 'automobile' },
    { emoji: '🚕', name: 'taxi' },
    { emoji: '🚙', name: 'sport utility vehicle' },
    { emoji: '🚌', name: 'bus' },
    { emoji: '🚎', name: 'trolleybus' },
    { emoji: '🏎️', name: 'racing car' },
    { emoji: '🚓', name: 'police car' },
    { emoji: '🚑', name: 'ambulance' },
    { emoji: '🚒', name: 'fire engine' },
    { emoji: '🚐', name: 'minibus' },
    { emoji: '🚚', name: 'delivery truck' },
    { emoji: '🚛', name: 'articulated lorry' },
    { emoji: '🚜', name: 'tractor' },
    { emoji: '🛴', name: 'kick scooter' },
    { emoji: '🚲', name: 'bicycle' },
    { emoji: '🛵', name: 'motor scooter' },
    { emoji: '🏍️', name: 'motorcycle' },
    { emoji: '🛺', name: 'auto rickshaw' },
    { emoji: '🚨', name: 'police car light' },
    { emoji: '🚠', name: 'mountain cableway' },
    { emoji: '🚡', name: 'aerial tramway' },
    { emoji: '🚃', name: 'railway car' },
    { emoji: '🚋', name: 'tram car' },
    { emoji: '🚞', name: 'mountain railway' },
    { emoji: '🚝', name: 'monorail' },
    { emoji: '🚄', name: 'high-speed train' },
    { emoji: '🚅', name: 'bullet train' },
    { emoji: '🚈', name: 'light rail' },
    { emoji: '🚂', name: 'locomotive' },
    { emoji: '🚆', name: 'train' },
    { emoji: '🚇', name: 'metro' },
    { emoji: '🚊', name: 'tram' },
    { emoji: '🚉', name: 'station' },
    { emoji: '🚁', name: 'helicopter' },
    { emoji: '🛸', name: 'flying saucer' },
    { emoji: '🚀', name: 'rocket' },
    { emoji: '🛫', name: 'airplane departure' },
    { emoji: '🛬', name: 'airplane arrival' },
    { emoji: '✈️', name: 'airplane' },
    { emoji: '🛩️', name: 'small airplane' },
    { emoji: '🛰️', name: 'satellite' },
    { emoji: '🚤', name: 'speedboat' },
    { emoji: '🛥️', name: 'motor boat' },
    { emoji: '🛳️', name: 'passenger ship' },
    { emoji: '⛴️', name: 'ferry' },
    { emoji: '🚢', name: 'ship' },
    { emoji: '⚓', name: 'anchor' },
    { emoji: '⛵', name: 'sailboat' },
    { emoji: '🛶', name: 'canoe' },
    { emoji: '🗺️', name: 'world map' },
    { emoji: '🗿', name: 'moai' },
    { emoji: '🗽', name: 'Statue of Liberty' },
    { emoji: '🗼', name: 'Tokyo tower' },
    { emoji: '🏰', name: 'castle' },
    { emoji: '🏯', name: 'Japanese castle' },
    { emoji: '🏟️', name: 'stadium' },
    { emoji: '🏗️', name: 'building construction' },
    { emoji: '🏠', name: 'house' },
    { emoji: '🏡', name: 'house with garden' },
    { emoji: '🏢', name: 'office building' },
    { emoji: '🏣', name: 'Japanese post office' },
    { emoji: '🏤', name: 'post office' },
    { emoji: '🏥', name: 'hospital' },
    { emoji: '🏦', name: 'bank' },
    { emoji: '🏨', name: 'hotel' },
    { emoji: '🏪', name: 'convenience store' },
    { emoji: '🏫', name: 'school' },
    { emoji: '🏬', name: 'department store' },
    { emoji: '🏭', name: 'factory' },
    { emoji: '💒', name: 'wedding' },
    { emoji: '⛪', name: 'church' },
    { emoji: '🕌', name: 'mosque' },
    { emoji: '🛕', name: 'hindu temple' },
    { emoji: '🕍', name: 'synagogue' },
    { emoji: '⛩️', name: 'shinto shrine' },
    { emoji: '🕋', name: 'kaaba' },
    { emoji: '⛲', name: 'fountain' },
    { emoji: '⛺', name: 'tent' },
    { emoji: '🌁', name: 'foggy' },
    { emoji: '🌃', name: 'night with stars' },
    { emoji: '🏙️', name: 'cityscape' },
    { emoji: '🌄', name: 'sunrise over mountains' },
    { emoji: '🌅', name: 'sunrise' },
    { emoji: '🌆', name: 'cityscape at dusk' },
    { emoji: '🌇', name: 'sunset' },
    { emoji: '🌉', name: 'bridge at night' },
    { emoji: '♨️', name: 'hot springs' },
    { emoji: '🎠', name: 'carousel horse' },
    { emoji: '🎡', name: 'ferris wheel' },
    { emoji: '🎢', name: 'roller coaster' },
    { emoji: '💈', name: 'barber pole' },
    { emoji: '🎪', name: 'circus tent' },
    { emoji: '🚏', name: 'bus stop' },
    { emoji: '🛣️', name: 'motorway' },
    { emoji: '🛤️', name: 'railway track' },
    { emoji: '⛽', name: 'fuel pump' },
    { emoji: '🚥', name: 'horizontal traffic light' },
    { emoji: '🚦', name: 'vertical traffic light' },
    { emoji: '🛑', name: 'stop sign' },
    { emoji: '🚧', name: 'construction' },
    { emoji: '🛎️', name: 'bellhop bell' },
    { emoji: '🧳', name: 'luggage' },
    { emoji: '⌛', name: 'hourglass done' },
    { emoji: '⏳', name: 'hourglass not done' },
    { emoji: '⌚', name: 'watch' },
    { emoji: '⏰', name: 'alarm clock' },
    { emoji: '⏱️', name: 'stopwatch' },
    { emoji: '⏲️', name: 'timer clock' },
    { emoji: '🕰️', name: 'mantelpiece clock' },
    { emoji: '🕛', name: 'twelve o\'clock' },
    { emoji: '🕐', name: 'one o\'clock' },
    { emoji: '🕑', name: 'two o\'clock' },
    { emoji: '🕒', name: 'three o\'clock' },
    { emoji: '🕓', name: 'four o\'clock' },
    { emoji: '🕔', name: 'five o\'clock' },
    { emoji: '🕕', name: 'six o\'clock' },
    { emoji: '🕖', name: 'seven o\'clock' },
    { emoji: '🕗', name: 'eight o\'clock' },
    { emoji: '🕘', name: 'nine o\'clock' },
    { emoji: '🕙', name: 'ten o\'clock' },
    { emoji: '🕚', name: 'eleven o\'clock' },
  ],
  objects: [
    { emoji: '⌚', name: 'watch' },
    { emoji: '📱', name: 'mobile phone' },
    { emoji: '📲', name: 'mobile phone with arrow' },
    { emoji: '💻', name: 'laptop' },
    { emoji: '⌨️', name: 'keyboard' },
    { emoji: '🖥️', name: 'desktop computer' },
    { emoji: '🖨️', name: 'printer' },
    { emoji: '🖱️', name: 'computer mouse' },
    { emoji: '💽', name: 'computer disk' },
    { emoji: '💾', name: 'floppy disk' },
    { emoji: '💿', name: 'optical disk' },
    { emoji: '📀', name: 'dvd' },
    { emoji: '📼', name: 'videocassette' },
    { emoji: '📷', name: 'camera' },
    { emoji: '📸', name: 'camera with flash' },
    { emoji: '📹', name: 'video camera' },
    { emoji: '🎥', name: 'movie camera' },
    { emoji: '📽️', name: 'film projector' },
    { emoji: '🎬', name: 'clapper board' },
    { emoji: '📺', name: 'television' },
    { emoji: '📻', name: 'radio' },
    { emoji: '🎙️', name: 'studio microphone' },
    { emoji: '🎚️', name: 'level slider' },
    { emoji: '🎛️', name: 'control knobs' },
    { emoji: '📡', name: 'satellite antenna' },
    { emoji: '🔋', name: 'battery' },
    { emoji: '🔌', name: 'electric plug' },
    { emoji: '💡', name: 'light bulb' },
    { emoji: '🔦', name: 'flashlight' },
    { emoji: '🕯️', name: 'candle' },
    { emoji: '🧯', name: 'fire extinguisher' },
    { emoji: '🛢️', name: 'oil drum' },
    { emoji: '💸', name: 'money with wings' },
    { emoji: '💵', name: 'dollar banknote' },
    { emoji: '💴', name: 'yen banknote' },
    { emoji: '💶', name: 'euro banknote' },
    { emoji: '💷', name: 'pound banknote' },
    { emoji: '💰', name: 'money bag' },
    { emoji: '💳', name: 'credit card' },
    { emoji: '🧾', name: 'receipt' },
    { emoji: '💎', name: 'gem stone' },
    { emoji: '⚖️', name: 'balance scale' },
    { emoji: '🧰', name: 'toolbox' },
    { emoji: '🔧', name: 'wrench' },
    { emoji: '🔨', name: 'hammer' },
    { emoji: '⚒️', name: 'hammer and pick' },
    { emoji: '🛠️', name: 'hammer and wrench' },
    { emoji: '⛏️', name: 'pick' },
    { emoji: '🔩', name: 'nut and bolt' },
    { emoji: '⚙️', name: 'gear' },
    { emoji: '🔗', name: 'link' },
    { emoji: '⛓️', name: 'chains' },
    { emoji: '🧲', name: 'magnet' },
    { emoji: '🔫', name: 'water pistol' },
    { emoji: '💣', name: 'bomb' },
    { emoji: '🧨', name: 'firecracker' },
    { emoji: '🗡️', name: 'dagger' },
    { emoji: '⚔️', name: 'crossed swords' },
    { emoji: '🛡️', name: 'shield' },
    { emoji: '🚬', name: 'cigarette' },
    { emoji: '⚰️', name: 'coffin' },
    { emoji: '🪦', name: 'headstone' },
    { emoji: '⚱️', name: 'funeral urn' },
    { emoji: '🏺', name: 'amphora' },
    { emoji: '🔮', name: 'crystal ball' },
    { emoji: '📿', name: 'prayer beads' },
    { emoji: '🧿', name: 'nazar amulet' },
    { emoji: '⚗️', name: 'alembic' },
    { emoji: '🔭', name: 'telescope' },
    { emoji: '🔬', name: 'microscope' },
    { emoji: '🕳️', name: 'hole' },
    { emoji: '🩹', name: 'adhesive bandage' },
    { emoji: '🩺', name: 'stethoscope' },
    { emoji: '💊', name: 'pill' },
    { emoji: '💉', name: 'syringe' },
    { emoji: '🩸', name: 'drop of blood' },
    { emoji: '🧬', name: 'dna' },
    { emoji: '🦠', name: 'microbe' },
    { emoji: '🧫', name: 'petri dish' },
    { emoji: '🧪', name: 'test tube' },
    { emoji: '🌡️', name: 'thermometer' },
    { emoji: '🧹', name: 'broom' },
    { emoji: '🧺', name: 'basket' },
    { emoji: '🧻', name: 'roll of paper' },
    { emoji: '🚽', name: 'toilet' },
    { emoji: '🚿', name: 'shower' },
    { emoji: '🛁', name: 'bathtub' },
    { emoji: '🧼', name: 'soap' },
    { emoji: '🪥', name: 'toothbrush' },
    { emoji: '🪒', name: 'razor' },
    { emoji: '🧽', name: 'sponge' },
    { emoji: '🧴', name: 'lotion bottle' },
    { emoji: '🔑', name: 'key' },
    { emoji: '🗝️', name: 'old key' },
    { emoji: '🚪', name: 'door' },
    { emoji: '🪑', name: 'chair' },
    { emoji: '🛋️', name: 'couch and lamp' },
    { emoji: '🛏️', name: 'bed' },
    { emoji: '🧸', name: 'teddy bear' },
    { emoji: '🖼️', name: 'framed picture' },
    { emoji: '🛍️', name: 'shopping bags' },
    { emoji: '🛒', name: 'shopping cart' },
    { emoji: '🎁', name: 'wrapped gift' },
    { emoji: '🎈', name: 'balloon' },
    { emoji: '🎏', name: 'carp streamer' },
    { emoji: '🎀', name: 'ribbon' },
    { emoji: '🎊', name: 'confetti ball' },
    { emoji: '🎉', name: 'party popper' },
    { emoji: '🎎', name: 'Japanese dolls' },
    { emoji: '🏮', name: 'red paper lantern' },
    { emoji: '🎐', name: 'wind chime' },
    { emoji: '🧧', name: 'red envelope' },
    { emoji: '✉️', name: 'envelope' },
    { emoji: '📩', name: 'envelope with arrow' },
    { emoji: '📨', name: 'incoming envelope' },
    { emoji: '📧', name: 'e-mail' },
    { emoji: '💌', name: 'love letter' },
    { emoji: '📥', name: 'inbox tray' },
    { emoji: '📤', name: 'outbox tray' },
    { emoji: '📦', name: 'package' },
    { emoji: '🏷️', name: 'label' },
    { emoji: '📪', name: 'closed mailbox with lowered flag' },
    { emoji: '📫', name: 'closed mailbox with raised flag' },
    { emoji: '📬', name: 'open mailbox with raised flag' },
    { emoji: '📭', name: 'open mailbox with lowered flag' },
    { emoji: '📮', name: 'postbox' },
    { emoji: '🗳️', name: 'ballot box with ballot' },
    { emoji: '✏️', name: 'pencil' },
    { emoji: '✒️', name: 'black nib' },
    { emoji: '🖋️', name: 'fountain pen' },
    { emoji: '🖊️', name: 'pen' },
    { emoji: '🖌️', name: 'paintbrush' },
    { emoji: '🖍️', name: 'crayon' },
    { emoji: '📝', name: 'memo' },
    { emoji: '💼', name: 'briefcase' },
    { emoji: '📁', name: 'file folder' },
    { emoji: '📂', name: 'open file folder' },
    { emoji: '🗂️', name: 'card index dividers' },
    { emoji: '📅', name: 'calendar' },
    { emoji: '📆', name: 'tear-off calendar' },
    { emoji: '🗒️', name: 'spiral notepad' },
    { emoji: '🗓️', name: 'spiral calendar' },
    { emoji: '📇', name: 'card index' },
    { emoji: '📈', name: 'chart increasing' },
    { emoji: '📉', name: 'chart decreasing' },
    { emoji: '📊', name: 'bar chart' },
    { emoji: '📋', name: 'clipboard' },
    { emoji: '📌', name: 'pushpin' },
    { emoji: '📍', name: 'round pushpin' },
    { emoji: '📎', name: 'paperclip' },
    { emoji: '🖇️', name: 'linked paperclips' },
    { emoji: '📏', name: 'straight ruler' },
    { emoji: '📐', name: 'triangular ruler' },
    { emoji: '✂️', name: 'scissors' },
    { emoji: '🗃️', name: 'card file box' },
    { emoji: '🗄️', name: 'file cabinet' },
    { emoji: '🗑️', name: 'wastebasket' },
    { emoji: '🔒', name: 'locked' },
    { emoji: '🔓', name: 'unlocked' },
    { emoji: '🔏', name: 'locked with pen' },
    { emoji: '🔐', name: 'locked with key' },
  ],
  symbols: [
    { emoji: '❤️', name: 'red heart' },
    { emoji: '🧡', name: 'orange heart' },
    { emoji: '💛', name: 'yellow heart' },
    { emoji: '💚', name: 'green heart' },
    { emoji: '💙', name: 'blue heart' },
    { emoji: '💜', name: 'purple heart' },
    { emoji: '🖤', name: 'black heart' },
    { emoji: '🤍', name: 'white heart' },
    { emoji: '🤎', name: 'brown heart' },
    { emoji: '💔', name: 'broken heart' },
    { emoji: '❣️', name: 'heart exclamation' },
    { emoji: '💕', name: 'two hearts' },
    { emoji: '💞', name: 'revolving hearts' },
    { emoji: '💓', name: 'beating heart' },
    { emoji: '💗', name: 'growing heart' },
    { emoji: '💖', name: 'sparkling heart' },
    { emoji: '💘', name: 'heart with arrow' },
    { emoji: '💝', name: 'heart with ribbon' },
    { emoji: '💟', name: 'heart decoration' },
    { emoji: '☮️', name: 'peace symbol' },
    { emoji: '✝️', name: 'latin cross' },
    { emoji: '☪️', name: 'star and crescent' },
    { emoji: '🕉️', name: 'om' },
    { emoji: '☸️', name: 'wheel of dharma' },
    { emoji: '✡️', name: 'star of david' },
    { emoji: '🔯', name: 'dotted six-pointed star' },
    { emoji: '🕎', name: 'menorah' },
    { emoji: '☯️', name: 'yin yang' },
    { emoji: '☦️', name: 'orthodox cross' },
    { emoji: '🛐', name: 'place of worship' },
    { emoji: '⛎', name: 'ophiuchus' },
    { emoji: '♈', name: 'aries' },
    { emoji: '♉', name: 'taurus' },
    { emoji: '♊', name: 'gemini' },
    { emoji: '♋', name: 'cancer' },
    { emoji: '♌', name: 'leo' },
    { emoji: '♍', name: 'virgo' },
    { emoji: '♎', name: 'libra' },
    { emoji: '♏', name: 'scorpio' },
    { emoji: '♐', name: 'sagittarius' },
    { emoji: '♑', name: 'capricorn' },
    { emoji: '♒', name: 'aquarius' },
    { emoji: '♓', name: 'pisces' },
    { emoji: '⚛️', name: 'atom symbol' },
    { emoji: '🉑', name: 'Japanese acceptable button' },
    { emoji: '☢️', name: 'radioactive' },
    { emoji: '☣️', name: 'biohazard' },
    { emoji: '📴', name: 'mobile phone off' },
    { emoji: '📳', name: 'vibration mode' },
    { emoji: '🈶', name: 'Japanese not free of charge button' },
    { emoji: '🈚', name: 'Japanese free of charge button' },
    { emoji: '🈸', name: 'Japanese application button' },
    { emoji: '🈺', name: 'Japanese open for business button' },
    { emoji: '🈷️', name: 'Japanese monthly amount button' },
    { emoji: '✴️', name: 'eight-pointed star' },
    { emoji: '🆚', name: 'vs button' },
    { emoji: '💮', name: 'white flower' },
    { emoji: '🉐', name: 'Japanese bargain button' },
    { emoji: '㊙️', name: 'Japanese secret button' },
    { emoji: '㊗️', name: 'Japanese congratulations button' },
    { emoji: '🈴', name: 'Japanese passing grade button' },
    { emoji: '🈵', name: 'Japanese no vacancy button' },
    { emoji: '🈹', name: 'Japanese discount button' },
    { emoji: '🈲', name: 'Japanese prohibited button' },
    { emoji: '🅰️', name: 'a button' },
    { emoji: '🅱️', name: 'b button' },
    { emoji: '🆎', name: 'ab button' },
    { emoji: '🆑', name: 'cl button' },
    { emoji: '🆒', name: 'cool button' },
    { emoji: '🆓', name: 'free button' },
    { emoji: 'ℹ️', name: 'information' },
    { emoji: 'Ⓜ️', name: 'circled m' },
    { emoji: '🆕', name: 'new button' },
    { emoji: '🆖', name: 'ng button' },
    { emoji: '🅾️', name: 'o button' },
    { emoji: '🆗', name: 'ok button' },
    { emoji: '🅿️', name: 'p button' },
    { emoji: '🆘', name: 'sos button' },
    { emoji: '🆙', name: 'up button' },
    { emoji: '🈁', name: 'Japanese here button' },
    { emoji: '🈂️', name: 'Japanese service charge button' },
    { emoji: '🔴', name: 'red circle' },
    { emoji: '🟠', name: 'orange circle' },
    { emoji: '🟡', name: 'yellow circle' },
    { emoji: '🟢', name: 'green circle' },
    { emoji: '🔵', name: 'blue circle' },
    { emoji: '🟣', name: 'purple circle' },
    { emoji: '🟤', name: 'brown circle' },
    { emoji: '⚫', name: 'black circle' },
    { emoji: '⚪', name: 'white circle' },
    { emoji: '🟥', name: 'red square' },
    { emoji: '🟧', name: 'orange square' },
    { emoji: '🟨', name: 'yellow square' },
    { emoji: '🟩', name: 'green square' },
    { emoji: '🟦', name: 'blue square' },
    { emoji: '🟪', name: 'purple square' },
    { emoji: '🟫', name: 'brown square' },
    { emoji: '⬛', name: 'black large square' },
    { emoji: '⬜', name: 'white large square' },
    { emoji: '◼️', name: 'black medium square' },
    { emoji: '◻️', name: 'white medium square' },
    { emoji: '◾', name: 'black medium-small square' },
    { emoji: '◽', name: 'white medium-small square' },
    { emoji: '▪️', name: 'black small square' },
    { emoji: '▫️', name: 'white small square' },
    { emoji: '🔶', name: 'large orange diamond' },
    { emoji: '🔷', name: 'large blue diamond' },
    { emoji: '🔸', name: 'small orange diamond' },
    { emoji: '🔹', name: 'small blue diamond' },
    { emoji: '🔺', name: 'red triangle pointed up' },
    { emoji: '🔻', name: 'red triangle pointed down' },
    { emoji: '💠', name: 'diamond with a dot' },
    { emoji: '🔘', name: 'radio button' },
    { emoji: '🔳', name: 'white square button' },
    { emoji: '🔲', name: 'black square button' },
    { emoji: '🏁', name: 'chequered flag' },
    { emoji: '🚩', name: 'triangular flag' },
    { emoji: '🎌', name: 'crossed flags' },
    { emoji: '🏴', name: 'black flag' },
    { emoji: '🏳️', name: 'white flag' },
    { emoji: '🏳️‍🌈', name: 'rainbow flag' },
    { emoji: '🏳️‍⚧️', name: 'transgender flag' },
    { emoji: '🏴‍☠️', name: 'pirate flag' },
  ],
  flags: [
    { emoji: '🇦🇨', name: 'flag: Ascension Island' },
    { emoji: '🇦🇩', name: 'flag: Andorra' },
    { emoji: '🇦🇪', name: 'flag: United Arab Emirates' },
    { emoji: '🇦🇫', name: 'flag: Afghanistan' },
    { emoji: '🇦🇬', name: 'flag: Antigua & Barbuda' },
    { emoji: '🇦🇮', name: 'flag: Anguilla' },
    { emoji: '🇦🇱', name: 'flag: Albania' },
    { emoji: '🇦🇲', name: 'flag: Armenia' },
    { emoji: '🇦🇴', name: 'flag: Angola' },
    { emoji: '🇦🇶', name: 'flag: Antarctica' },
    { emoji: '🇦🇷', name: 'flag: Argentina' },
    { emoji: '🇦🇸', name: 'flag: American Samoa' },
    { emoji: '🇦🇹', name: 'flag: Austria' },
    { emoji: '🇦🇺', name: 'flag: Australia' },
    { emoji: '🇦🇼', name: 'flag: Aruba' },
    { emoji: '🇦🇽', name: 'flag: Åland Islands' },
    { emoji: '🇦🇿', name: 'flag: Azerbaijan' },
    { emoji: '🇧🇦', name: 'flag: Bosnia & Herzegovina' },
    { emoji: '🇧🇧', name: 'flag: Barbados' },
    { emoji: '🇧🇩', name: 'flag: Bangladesh' },
    { emoji: '🇧🇪', name: 'flag: Belgium' },
    { emoji: '🇧🇫', name: 'flag: Burkina Faso' },
    { emoji: '🇧🇬', name: 'flag: Bulgaria' },
    { emoji: '🇧🇭', name: 'flag: Bahrain' },
    { emoji: '🇧🇮', name: 'flag: Burundi' },
    { emoji: '🇧🇯', name: 'flag: Benin' },
    { emoji: '🇧🇱', name: 'flag: St. Barthélemy' },
    { emoji: '🇧🇲', name: 'flag: Bermuda' },
    { emoji: '🇧🇳', name: 'flag: Brunei' },
    { emoji: '🇧🇴', name: 'flag: Bolivia' },
    { emoji: '🇧🇶', name: 'flag: Caribbean Netherlands' },
    { emoji: '🇧🇷', name: 'flag: Brazil' },
    { emoji: '🇧🇸', name: 'flag: Bahamas' },
    { emoji: '🇧🇹', name: 'flag: Bhutan' },
    { emoji: '🇧🇻', name: 'flag: Bouvet Island' },
    { emoji: '🇧🇼', name: 'flag: Botswana' },
    { emoji: '🇧🇾', name: 'flag: Belarus' },
    { emoji: '🇧🇿', name: 'flag: Belize' },
    { emoji: '🇨🇦', name: 'flag: Canada' },
    { emoji: '🇨🇨', name: 'flag: Cocos (Keeling) Islands' },
    { emoji: '🇨🇩', name: 'flag: Congo - Kinshasa' },
    { emoji: '🇨🇫', name: 'flag: Central African Republic' },
    { emoji: '🇨🇬', name: 'flag: Congo - Brazzaville' },
    { emoji: '🇨🇭', name: 'flag: Switzerland' },
    { emoji: '🇨🇮', name: 'flag: Côte d\'Ivoire' },
    { emoji: '🇨🇰', name: 'flag: Cook Islands' },
    { emoji: '🇨🇱', name: 'flag: Chile' },
    { emoji: '🇨🇲', name: 'flag: Cameroon' },
    { emoji: '🇨🇳', name: 'flag: China' },
    { emoji: '🇨🇴', name: 'flag: Colombia' },
    { emoji: '🇨🇵', name: 'flag: Clipperton Island' },
    { emoji: '🇨🇷', name: 'flag: Costa Rica' },
    { emoji: '🇨🇺', name: 'flag: Cuba' },
    { emoji: '🇨🇻', name: 'flag: Cape Verde' },
    { emoji: '🇨🇼', name: 'flag: Curaçao' },
    { emoji: '🇨🇽', name: 'flag: Christmas Island' },
    { emoji: '🇨🇾', name: 'flag: Cyprus' },
    { emoji: '🇨🇿', name: 'flag: Czechia' },
    { emoji: '🇩🇪', name: 'flag: Germany' },
    { emoji: '🇩🇬', name: 'flag: Diego Garcia' },
    { emoji: '🇩🇯', name: 'flag: Djibouti' },
    { emoji: '🇩🇰', name: 'flag: Denmark' },
    { emoji: '🇩🇲', name: 'flag: Dominica' },
    { emoji: '🇩🇴', name: 'flag: Dominican Republic' },
    { emoji: '🇩🇿', name: 'flag: Algeria' },
    { emoji: '🇪🇦', name: 'flag: Ceuta & Melilla' },
    { emoji: '🇪🇨', name: 'flag: Ecuador' },
    { emoji: '🇪🇪', name: 'flag: Estonia' },
    { emoji: '🇪🇬', name: 'flag: Egypt' },
    { emoji: '🇪🇭', name: 'flag: Western Sahara' },
    { emoji: '🇪🇷', name: 'flag: Eritrea' },
    { emoji: '🇪🇸', name: 'flag: Spain' },
    { emoji: '🇪🇹', name: 'flag: Ethiopia' },
    { emoji: '🇪🇺', name: 'flag: European Union' },
    { emoji: '🇫🇮', name: 'flag: Finland' },
    { emoji: '🇫🇯', name: 'flag: Fiji' },
    { emoji: '🇫🇰', name: 'flag: Falkland Islands' },
    { emoji: '🇫🇲', name: 'flag: Micronesia' },
    { emoji: '🇫🇴', name: 'flag: Faroe Islands' },
    { emoji: '🇫🇷', name: 'flag: France' },
    { emoji: '🇬🇦', name: 'flag: Gabon' },
    { emoji: '🇬🇧', name: 'flag: United Kingdom' },
    { emoji: '🇬🇩', name: 'flag: Grenada' },
    { emoji: '🇬🇪', name: 'flag: Georgia' },
    { emoji: '🇬🇫', name: 'flag: French Guiana' },
    { emoji: '🇬🇬', name: 'flag: Guernsey' },
    { emoji: '🇬🇭', name: 'flag: Ghana' },
    { emoji: '🇬🇮', name: 'flag: Gibraltar' },
    { emoji: '🇬🇱', name: 'flag: Greenland' },
    { emoji: '🇬🇲', name: 'flag: Gambia' },
    { emoji: '🇬🇳', name: 'flag: Guinea' },
    { emoji: '🇬🇵', name: 'flag: Guadeloupe' },
    { emoji: '🇬🇶', name: 'flag: Equatorial Guinea' },
    { emoji: '🇬🇷', name: 'flag: Greece' },
    { emoji: '🇬🇸', name: 'flag: South Georgia & South Sandwich Islands' },
    { emoji: '🇬🇹', name: 'flag: Guatemala' },
    { emoji: '🇬🇺', name: 'flag: Guam' },
    { emoji: '🇬🇼', name: 'flag: Guinea-Bissau' },
    { emoji: '🇬🇾', name: 'flag: Guyana' },
    { emoji: '🇭🇰', name: 'flag: Hong Kong SAR China' },
    { emoji: '🇭🇲', name: 'flag: Heard & McDonald Islands' },
    { emoji: '🇭🇳', name: 'flag: Honduras' },
    { emoji: '🇭🇷', name: 'flag: Croatia' },
    { emoji: '🇭🇹', name: 'flag: Haiti' },
    { emoji: '🇭🇺', name: 'flag: Hungary' },
    { emoji: '🇮🇨', name: 'flag: Canary Islands' },
    { emoji: '🇮🇩', name: 'flag: Indonesia' },
    { emoji: '🇮🇪', name: 'flag: Ireland' },
    { emoji: '🇮🇱', name: 'flag: Israel' },
    { emoji: '🇮🇲', name: 'flag: Isle of Man' },
    { emoji: '🇮🇳', name: 'flag: India' },
    { emoji: '🇮🇴', name: 'flag: British Indian Ocean Territory' },
    { emoji: '🇮🇶', name: 'flag: Iraq' },
    { emoji: '🇮🇷', name: 'flag: Iran' },
    { emoji: '🇮🇸', name: 'flag: Iceland' },
    { emoji: '🇮🇹', name: 'flag: Italy' },
    { emoji: '🇯🇪', name: 'flag: Jersey' },
    { emoji: '🇯🇲', name: 'flag: Jamaica' },
    { emoji: '🇯🇴', name: 'flag: Jordan' },
    { emoji: '🇯🇵', name: 'flag: Japan' },
    { emoji: '🇰🇪', name: 'flag: Kenya' },
    { emoji: '🇰🇬', name: 'flag: Kyrgyzstan' },
    { emoji: '🇰🇭', name: 'flag: Cambodia' },
    { emoji: '🇰🇮', name: 'flag: Kiribati' },
    { emoji: '🇰🇲', name: 'flag: Comoros' },
    { emoji: '🇰🇳', name: 'flag: St. Kitts & Nevis' },
    { emoji: '🇰🇵', name: 'flag: North Korea' },
    { emoji: '🇰🇷', name: 'flag: South Korea' },
    { emoji: '🇰🇼', name: 'flag: Kuwait' },
    { emoji: '🇰🇾', name: 'flag: Cayman Islands' },
    { emoji: '🇰🇿', name: 'flag: Kazakhstan' },
    { emoji: '🇱🇦', name: 'flag: Laos' },
    { emoji: '🇱🇧', name: 'flag: Lebanon' },
    { emoji: '🇱🇨', name: 'flag: St. Lucia' },
    { emoji: '🇱🇮', name: 'flag: Liechtenstein' },
    { emoji: '🇱🇰', name: 'flag: Sri Lanka' },
    { emoji: '🇱🇷', name: 'flag: Liberia' },
    { emoji: '🇱🇸', name: 'flag: Lesotho' },
    { emoji: '🇱🇹', name: 'flag: Lithuania' },
    { emoji: '🇱🇺', name: 'flag: Luxembourg' },
    { emoji: '🇱🇻', name: 'flag: Latvia' },
    { emoji: '🇱🇾', name: 'flag: Libya' },
    { emoji: '🇲🇦', name: 'flag: Morocco' },
    { emoji: '🇲🇨', name: 'flag: Monaco' },
    { emoji: '🇲🇩', name: 'flag: Moldova' },
    { emoji: '🇲🇪', name: 'flag: Montenegro' },
    { emoji: '🇲🇫', name: 'flag: St. Martin' },
    { emoji: '🇲🇬', name: 'flag: Madagascar' },
    { emoji: '🇲🇭', name: 'flag: Marshall Islands' },
    { emoji: '🇲🇰', name: 'flag: North Macedonia' },
    { emoji: '🇲🇱', name: 'flag: Mali' },
    { emoji: '🇲🇲', name: 'flag: Myanmar (Burma)' },
    { emoji: '🇲🇳', name: 'flag: Mongolia' },
    { emoji: '🇲🇴', name: 'flag: Macao SAR China' },
    { emoji: '🇲🇵', name: 'flag: Northern Mariana Islands' },
    { emoji: '🇲🇶', name: 'flag: Martinique' },
    { emoji: '🇲🇷', name: 'flag: Mauritania' },
    { emoji: '🇲🇸', name: 'flag: Montserrat' },
    { emoji: '🇲🇹', name: 'flag: Malta' },
    { emoji: '🇲🇺', name: 'flag: Mauritius' },
    { emoji: '🇲🇻', name: 'flag: Maldives' },
    { emoji: '🇲🇼', name: 'flag: Malawi' },
    { emoji: '🇲🇽', name: 'flag: Mexico' },
    { emoji: '🇲🇾', name: 'flag: Malaysia' },
    { emoji: '🇲🇿', name: 'flag: Mozambique' },
    { emoji: '🇳🇦', name: 'flag: Namibia' },
    { emoji: '🇳🇨', name: 'flag: New Caledonia' },
    { emoji: '🇳🇪', name: 'flag: Niger' },
    { emoji: '🇳🇫', name: 'flag: Norfolk Island' },
    { emoji: '🇳🇬', name: 'flag: Nigeria' },
    { emoji: '🇳🇮', name: 'flag: Nicaragua' },
    { emoji: '🇳🇱', name: 'flag: Netherlands' },
    { emoji: '🇳🇴', name: 'flag: Norway' },
    { emoji: '🇳🇵', name: 'flag: Nepal' },
    { emoji: '🇳🇷', name: 'flag: Nauru' },
    { emoji: '🇳🇺', name: 'flag: Niue' },
    { emoji: '🇳🇿', name: 'flag: New Zealand' },
    { emoji: '🇴🇲', name: 'flag: Oman' },
    { emoji: '🇵🇦', name: 'flag: Panama' },
    { emoji: '🇵🇪', name: 'flag: Peru' },
    { emoji: '🇵🇫', name: 'flag: French Polynesia' },
    { emoji: '🇵🇬', name: 'flag: Papua New Guinea' },
    { emoji: '🇵🇭', name: 'flag: Philippines' },
    { emoji: '🇵🇰', name: 'flag: Pakistan' },
    { emoji: '🇵🇱', name: 'flag: Poland' },
    { emoji: '🇵🇲', name: 'flag: St. Pierre & Miquelon' },
    { emoji: '🇵🇳', name: 'flag: Pitcairn Islands' },
    { emoji: '🇵🇷', name: 'flag: Puerto Rico' },
    { emoji: '🇵🇸', name: 'flag: Palestinian Territories' },
    { emoji: '🇵🇹', name: 'flag: Portugal' },
    { emoji: '🇵🇼', name: 'flag: Palau' },
    { emoji: '🇵🇾', name: 'flag: Paraguay' },
    { emoji: '🇶🇦', name: 'flag: Qatar' },
    { emoji: '🇷🇪', name: 'flag: Réunion' },
    { emoji: '🇷🇴', name: 'flag: Romania' },
    { emoji: '🇷🇸', name: 'flag: Serbia' },
    { emoji: '🇷🇺', name: 'flag: Russia' },
    { emoji: '🇷🇼', name: 'flag: Rwanda' },
    { emoji: '🇸🇦', name: 'flag: Saudi Arabia' },
    { emoji: '🇸🇧', name: 'flag: Solomon Islands' },
    { emoji: '🇸🇨', name: 'flag: Seychelles' },
    { emoji: '🇸🇩', name: 'flag: Sudan' },
    { emoji: '🇸🇪', name: 'flag: Sweden' },
    { emoji: '🇸🇬', name: 'flag: Singapore' },
    { emoji: '🇸🇭', name: 'flag: St. Helena' },
    { emoji: '🇸🇮', name: 'flag: Slovenia' },
    { emoji: '🇸🇯', name: 'flag: Svalbard & Jan Mayen' },
    { emoji: '🇸🇰', name: 'flag: Slovakia' },
    { emoji: '🇸🇱', name: 'flag: Sierra Leone' },
    { emoji: '🇸🇲', name: 'flag: San Marino' },
    { emoji: '🇸🇳', name: 'flag: Senegal' },
    { emoji: '🇸🇴', name: 'flag: Somalia' },
    { emoji: '🇸🇷', name: 'flag: Suriname' },
    { emoji: '🇸🇸', name: 'flag: South Sudan' },
    { emoji: '🇸🇹', name: 'flag: São Tomé & Príncipe' },
    { emoji: '🇸🇻', name: 'flag: El Salvador' },
    { emoji: '🇸🇽', name: 'flag: Sint Maarten' },
    { emoji: '🇸🇾', name: 'flag: Syria' },
    { emoji: '🇸🇿', name: 'flag: Eswatini' },
    { emoji: '🇹🇦', name: 'flag: Tristan da Cunha' },
    { emoji: '🇹🇨', name: 'flag: Turks & Caicos Islands' },
    { emoji: '🇹🇩', name: 'flag: Chad' },
    { emoji: '🇹🇫', name: 'flag: French Southern Territories' },
    { emoji: '🇹🇬', name: 'flag: Togo' },
    { emoji: '🇹🇭', name: 'flag: Thailand' },
    { emoji: '🇹🇯', name: 'flag: Tajikistan' },
    { emoji: '🇹🇰', name: 'flag: Tokelau' },
    { emoji: '🇹🇱', name: 'flag: Timor-Leste' },
    { emoji: '🇹🇲', name: 'flag: Turkmenistan' },
    { emoji: '🇹🇳', name: 'flag: Tunisia' },
    { emoji: '🇹🇴', name: 'flag: Tonga' },
    { emoji: '🇹🇷', name: 'flag: Turkey' },
    { emoji: '🇹🇹', name: 'flag: Trinidad & Tobago' },
    { emoji: '🇹🇻', name: 'flag: Tuvalu' },
    { emoji: '🇹🇼', name: 'flag: Taiwan' },
    { emoji: '🇹🇿', name: 'flag: Tanzania' },
    { emoji: '🇺🇦', name: 'flag: Ukraine' },
    { emoji: '🇺🇬', name: 'flag: Uganda' },
    { emoji: '🇺🇲', name: 'flag: U.S. Outlying Islands' },
    { emoji: '🇺🇳', name: 'flag: United Nations' },
    { emoji: '🇺🇸', name: 'flag: United States' },
    { emoji: '🇺🇾', name: 'flag: Uruguay' },
    { emoji: '🇺🇿', name: 'flag: Uzbekistan' },
    { emoji: '🇻🇦', name: 'flag: Vatican City' },
    { emoji: '🇻🇨', name: 'flag: St. Vincent & Grenadines' },
    { emoji: '🇻🇪', name: 'flag: Venezuela' },
    { emoji: '🇻🇬', name: 'flag: British Virgin Islands' },
    { emoji: '🇻🇮', name: 'flag: U.S. Virgin Islands' },
    { emoji: '🇻🇳', name: 'flag: Vietnam' },
    { emoji: '🇻🇺', name: 'flag: Vanuatu' },
    { emoji: '🇼🇫', name: 'flag: Wallis & Futuna' },
    { emoji: '🇼🇸', name: 'flag: Samoa' },
    { emoji: '🇽🇰', name: 'flag: Kosovo' },
    { emoji: '🇾🇪', name: 'flag: Yemen' },
    { emoji: '🇾🇹', name: 'flag: Mayotte' },
    { emoji: '🇿🇦', name: 'flag: South Africa' },
    { emoji: '🇿🇲', name: 'flag: Zambia' },
    { emoji: '🇿🇼', name: 'flag: Zimbabwe' },
  ],
};